services:
  # Guacamole Daemon - Needed for Guacamole
  guacd:
    image: guacamole/guacd
    container_name: guacd
    user: "$PUID:$PGID" # Specify user and group ID
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
