services:
  # Guacamole - Remote desktop, SSH, on Telnet on any HTML5 Browser
  # Create all databases and tables first
  guacamole:
    image: guacamole/guacamole:latest
    user: "root:root" # Needed but not appreciated
    container_name: guacamole
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_network
      - default
    # ports:
    #   - "$GUACAMOLE_PORT:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mariadb
      MYSQL_PORT: $MARIADB_PORT
      MYSQL_DATABASE_FILE: /run/secrets/guac_db_name
      MYSQL_USER_FILE: /run/secrets/guac_mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/guac_mysql_password
    secrets:
      - guac_db_name
      - guac_mysql_user
      - guac_mysql_password
    volumes:
      # Workaround for guacamole/guacamole:latest: MYSQL_*(_FILE) env vars are no longer translated into mysql-* properties,
      # causing JDBC auth to fail with “Retrieval of database credentials failed”.
      # This script reads Docker secrets (/run/secrets/...) and writes /etc/guacamole/guacamole.properties with mysql-* creds
      # so the generated /tmp/guacamole-home.*/guacamole.properties always contains DB settings on every restart/recreate.
      # Mounted as a single file (not the whole dir) to keep upstream entrypoint.d scripts; "050-" makes it run early.

      # Mount ONLY the script into Guacamole's built-in entrypoint.d dir (do NOT replace the whole dir)
      - $DOCKERDIR/appdata/guacamole/entrypoint.d/10-pin-mysql-props.sh:/opt/guacamole/entrypoint.d/050-pin-mysql-props.sh:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.guacamole-rtr.entrypoints=https"
      - "traefik.http.routers.guacamole-rtr.rule=Host(`guac.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.guacamole-rtr.middlewares=chain-authelia@file,add-guacamole"
      - "traefik.http.middlewares.add-guacamole.addPrefix.prefix=/guacamole"
      ## HTTP Services
      - "traefik.http.routers.guacamole-rtr.service=guacamole-svc"
      - "traefik.http.services.guacamole-svc.loadbalancer.server.port=8080"
