services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: "no"
    security_opt:
      - no-new-privileges:true
    networks:
      - t2_proxy
      - socket_proxy
    # ports:
    #   - '7575:7575'
    volumes:
      - $DOCKERDIR/appdata/homarr/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - $DOCKERDIR/appdata/homarr/configs:/app/data/configs
      - $DOCKERDIR/appdata/homarr/icons:/app/public/icons
      - $DOCKERDIR/appdata/homarr/data:/data
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homarr-rtr.entrypoints=https"
      - "traefik.http.routers.homarr-rtr.rule=Host(`$DOMAINNAME0`,`www.$DOMAINNAME0`)"
      - "traefik.http.routers.homarr-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.homarr-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.homarr-rtr.service=homarr-svc"
      - "traefik.http.services.homarr-svc.loadbalancer.server.port=7575"
