services:
  # MariaDB - MySQL Database
  # After starting container for first time dexec and mysqladmin -u root password <password>
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: linuxserver/mariadb:latest
    ports:
      - "$MARIADB_PORT:3306"
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_network
      - nextcloud
      - photoprism
    volumes:
      - $DOCKERDIR/appdata/mariadb/data:/config
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password # Not taking this pw during initialization
    secrets:
      - mysql_root_password
