services:
  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    command: -H tcp://socket-proxy:2375
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_network
      - socket_proxy
    volumes:
      - $DOCKERDIR/appdata/portainer/data:/data
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers for API Key Bypass
      - "traefik.http.routers.portainer-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.portainer-rtr-bypass.rule=Host(`portainer.$DOMAINNAME0`) && Header(`X-Api-Key`, `$PORTAINER_API_KEY`)"
      - "traefik.http.routers.portainer-rtr-bypass.priority=100"
      - "traefik.http.routers.portainer-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.portainer-rtr-bypass.service=portainer-svc"
      ## Standard HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME0`)"
      - "traefik.http.routers.portainer-rtr.priority=99"
      - "traefik.http.routers.portainer-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      ## HTTP Services
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
