services:
  # Speeds up Nextcloud by reducing the time spent "looking" for things
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    hostname: redis
    security_opt:
      - no-new-privileges:true
    # SOLVE PASSWORD HANDLING
    #entrypoint: redis-server --appendonly yes --requirepass $REDIS_PASSWORD --maxmemory 512mb --maxmemory-policy allkeys-lru
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - nextcloud
    ports:
      - "$REDIS_PORT:6379"
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
