services:
  # Speeds up Nextcloud by reducing the time spent "looking" for things
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    hostname: redis
    security_opt:
      - no-new-privileges:true
    command: [
      "redis-server",
      "--bind", "0.0.0.0",
      "--appendonly", "yes",
      "--requirepass", "$REDIS_PASSWORD",
      "--maxmemory", "512mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    networks:
      - redis
    ports:
      - "$REDIS_PORT:6379"
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
