services:
  # Redis Commander - Redis Management Tool
  rediscommander:
    container_name: rediscommander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - "$REDISCOMMANDER_PORT:8081"
    environment:
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_HOST=$SERVER_IP
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.rediscommander-rtr.entrypoints=https"
      - "traefik.http.routers.rediscommander-rtr.rule=Host(`rediscommander.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.rediscommander-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.rediscommander-rtr.service=rediscommander-svc"
      - "traefik.http.services.rediscommander-svc.loadbalancer.server.port=8081"