services:
  # Tdarr Node - Transcoder Node
  tdarr-node1:
    image: haveagitgat/tdarr_node:latest
    container_name: tdarr-node1
    restart: "no"
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
      nodeID: Node1
      nodeIP: tdarr-node1 # or hostname
      nodePort: 8267
      serverIP: tdarr # or hostname
      serverPort: 8266
    volumes:
      - $DOCKERDIR/appdata/tdarr/configs:/app/configs
      - $DOCKERDIR/appdata/tdarr/logs:/app/logs
      - $DOCKERDIR/appdata/tdarr/transcode:/data/temp
      - $DATADIR/media:/data/media:ro
      - $DATADIR/media/transcoded:/data/output
