services:
  # TransmissionBT - Torrent Downloader
  transmission-vpn:
    image: haugene/transmission-openvpn:latest
    #image: linuxserver/transmission:latest
    container_name: transmission-vpn
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      traefik_network:
        ipv4_address: 192.168.90.169
    # ports:
    #  - "$TRANSMISSION_PORT:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - dev/net/tun:/dev/net/tun
    # dns:
    #   - 1.1.1.1
    #   - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/transmission-vpn/data:/data
      - $DOCKERDIR/appdata/transmission-vpn/config:/config
      - $DOCKERDIR/appdata/transmission-vpn/config_pia:/etc/openvpn/custom/
      - $DATADIR/torrents:/data/torrents
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      OPENVPN_PROVIDER: custom
      OPENVPN_CONFIG: openvpn
      # OPENVPN_USERNAME: $PIA_USERNAME
      # OPENVPN_PASSWORD: $PIA_PASSWORD
      LOCAL_NETWORK: "$LOCAL_NETWORK"
      UMASK_SET: 2
      TRANSMISSION_WEB_UI: flood-for-transmission
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "false"
      TRANSMISSION_RPC_HOST_WHITELIST: "127.0.0.1,$SERVER_IP"
      #RPC_CREDS: /run/secrets/rpc_creds
      #TRANSMISSION_RPC_USERNAME: $TRANSMISSION_RPC_USERNAME
      #TRANSMISSION_RPC_PASSWORD: $TRANSMISSION_RPC_PASSWORD
      TRANSMISSION_UMASK: 002
      TRANSMISSION_RATIO_LIMIT: 0.01
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_DOWN: 40000
      TRANSMISSION_ALT_SPEED_ENABLED: "false"
      TRANSMISSION_ALT_SPEED_UP: 250
      TRANSMISSION_SPEED_LIMIT_DOWN: 100000
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP: 500
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_INCOMPLETE_DIR: /data/torrents/incoming
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_WATCH_DIR: /data/torrents/watch
      TRANSMISSION_WATCH_DIR_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_DIR: /data/torrents/completed
      LOG_TO_STDOUT: "true"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.transmission-vpn-rtr.entrypoints=https"
      - "traefik.http.routers.transmission-vpn-rtr.rule=Host(`transmission.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.transmission-vpn-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.transmission-vpn-rtr.service=transmission-vpn-svc"
      - "traefik.http.services.transmission-vpn-svc.loadbalancer.server.port=9091"