services:
  # Vaultwarden - Password Vault
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    networks:
      - traefik_network
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "$BITWARDEN_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/vaultwarden:/data
      #- /var/log/docker:/var/log/docker
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SIGNUPS_ALLOWED=false # Change to false after first login
      - INVITATIONS_ALLOWED=false
      - WEBSOCKET_ENABLED=true
      #- LOG_FILE=/var/log/docker/vaultwarden.log
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=$SMTP_EMAIL
      - SMTP_PORT=587
      #- SMTP_SSL=true
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=$SMTP_EMAIL
      - SMTP_PASSWORD=$SMTP_PASS
      - DOMAIN=https://vaultwarden.$DOMAINNAME0
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vaultwarden-ui.entrypoints=https"
      - "traefik.http.routers.vaultwarden-ui.rule=Host(`vaultwarden.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.vaultwarden-ui.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.vaultwarden-ui.service=vaultwarden-ui"
      - "traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80"
      ## HTTP Routers
      - "traefik.http.routers.vaultwarden-websocket-https.entrypoints=https"
      - "traefik.http.routers.vaultwarden-websocket-https.rule=Host(`vaultwarden.$DOMAINNAME0`) && Path(`/notifications/hub`)"
      ## Middlewares
      - "traefik.http.routers.vaultwarden-websocket-https.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.vaultwarden-websocket-https.service=vaultwarden-websocket"
      - "traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012" 